### ISSUE TITLE
I'd like to work with the design =)

### ISSUE THREAD

**Issue by fabiyamada** [Sleepe-Owl/sleepe-owl-design#1]
Hello! I'd like to work with the logo and all the design needs. Let me know your idea so I can work on it and if you like you keep it ;D
greetings!

**Comment by patricktailor** [comment]
Hi, Can you give me a e-mail address? :)

**Comment by fabiyamada** [comment]
sure, acevedoyamada@gmail.com or if you prefer we can talk on discord chat: fabiyamada#2178 for more fluid communication.
